### ISSUE TITLE
Allow for WWW URLs

### ISSUE THREAD

**Issue by jbyman** [jbyman/CrisisConnector#36]
Strangely, [www.crisisconnect.live](https://ww.crisisconnect.live) doesn't work with the `www` in the front of the URL. Rather _only_ naked URLs work. We should allow `www` in front of the DNS locator.

**Comment by chiragsamtani** [comment]
The review comment in this PR: https://github.com/jbyman/covid-hackathon/pull/20/files should fix this issue.

**Comment by karishay** [comment]
www.crisisconnect.live does not work but the other domains do.
